name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Retrieve Assembly Versions
        id: retrieve-versions
        run: |
          assemblyVersion = $(grep -oPm1 "(?<=<AssemblyVersion>)[^<]+" src/FScrobble.Shell/FScrobble.Shell.fsproj)
          assemblyFileVersion = $(grep -oPm1 "(?<=<AssemblyFileVersion>)[^<]+" src/FScrobble.Shell/FScrobble.Shell.fsproj)
          echo "Assembly Version: $assemblyVersion"
          echo "Assembly File Version: $assemblyFileVersion"
          echo "assembly_version=$assemblyVersion" >> GITHUB_OUTPUT
          echo "assembly_file_version=$assemblyFileVersion" >> GITHUB_OUTPUT
      
      - name: Create git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com" 
          git tag -a ${{ steps.retrieve-versions.outputs.assembly_version }} -m "Release version ${{ steps.retrieve-versions.outputs.assembly_version }}"
          git push origin ${{ steps.retrieve-versions.outputs.assembly_version }}

      - name: Push all tags
        run: git push --tags

      - name: Restore dependencies
        run: dotnet restore src/FScrobble.Shell/FScrobble.Shell.fsproj

      - name: Build project
        run: dotnet build src/FScrobble.Shell/FScrobble.Shell.fsproj --configuration Release /p:BuildNumber=${{ github.run_number }}

      - name: Publish project
        run: dotnet publish src/FScrobble.Shell/FScrobble.Shell.fsproj -r linux-x64 --configuration Release --self-contained true --output ./publish


      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FScrobble-linux-x64
          path: ./publish

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}